#! /bin/sh

echo "Starting bspwm..." > $HOME/.config/bspwm/log

sxhkd &

bspc monitor -d 01 02 03 04 05 06 07 08 09 10

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/setbackground.sh >> $HOME/.config/bspwm/log

$HOME/.config/polybar/launch.sh >> $HOME/.config/bspwm/log